### ISSUE TITLE
Line 97 in 2904927

### ISSUE THREAD

**Issue by iwahiropuzzles** [kkondo1981/aglm#21]
Not important issue.
https://github.com/kkondo1981/aglm/blob/2904927d63b821765cf03254da15a24db77d6fba/R/binning.R#L97
In `breaks=c(-Inf, breaks, Inf)`, the original `breaks` may have `-Inf` and/or `Inf`, which will cause an error.
In fact, I once got an error message for this reason in using aglm. 
So I think the right hand is better to be `unique(c(-Inf, breaks, Inf))`.

**Comment by kkondo1981** [comment]
Thanks for your feedback.

In fact, I believe that this is not an error but matter of specification or definition of custom binning.

As your understanding, aglm() currently do not assume custom binning with infinite or duplicated elements. (In addition, aglm() also assume that `breaks` are sorted in ascending order.)

If allowing such cases, I think it's better to modify newInput() in aglm-input.R to standardize `breaks` before passed to aglm functions, so that each custom binning has no infinite or duplicated elements.

For example, 

https://github.com/kkondo1981/aglm/blob/2904927d63b821765cf03254da15a24db77d6fba/R/aglm-input.R#L169

is modified as below:

> breaks <- bins_list[[i]]
> vars_info[[idx]]$OD_info$breaks <- unique(sort(breaks[is.finite(breaks)]))

Please could you tell me if there is any problem.
